import { MainContainer } from "@/components/";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat to playlist</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center">
        <MainContainer />
      </main>
    </>
  );
}
